### PR TITLE
Add support for non-diagonal noise and other fixes

### LINKED ISSUE #205: Add a section to the manual on how to use the lower level API for lower overhead
@utkarsh530 can you fill this out?

### PR DESCRIPTION
**Pull request by utkarsh530**
Also
Fixes #205

### CODE REVIEW

File: src/solve.jl [hunk 1]
```diff
@@ -171,3 +171,11 @@ function vectorized_asolve(probs, prob::ODEProblem, alg;
     #EDIT: Done when using with DiffEqGPU
     ts, us
 end
+
+function vectorized_asolve(probs, prob::SDEProblem, alg;
+                           dt, saveat = nothing,
+                           save_everystep = true,
+                           debug = false,
+                           kwargs...)
+    error("Adaptive time-stepping is not supported yet.")
```
Comment (ChrisRackauckas) [inline src/solve.jl:180]:
```suggestion
    error("Adaptive time-stepping is not supported yet with GPUEM.")
```
